language: python
env:
  global:
    - PYTHONUNBUFFERED=1
stages:
  - name: test
  - name: build wheels
jobs:
  fast_finish: true
  include:
  - stage: test
    before_install: &install_hyperscan
      - cd /tmp
      - wget http://downloads.sourceforge.net/project/boost/boost/1.57.0/boost_1_57_0.tar.bz2
      - tar xjf boost_1_57_0.tar.bz2
      - cd boost_1_57_0
      - ./bootstrap.sh --prefix=/usr
      - ./b2 -j4
      - sudo ./b2 install
      - pip install -U pip wheel
      - git clone https://github.com/01org/hyperscan.git
      - mkdir -p hyperscan/build
      - cd hyperscan/build
      - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON ../
      - make -j4
      - sudo make install
      - cd $TRAVIS_BUILD_DIR
    sudo: required
    python:
      - "2.7"
      - "3.4"
      - "3.5"
      - "3.6"
      - "pypy"
      - "pypy3"
    install:
      - pip install -U tox-travis
    script: tox
  - stage: build wheels
    sudo: required
    before_install: *install_hyperscan
    python:
      - "2.7"
      - "3.4"
      - "3.5"
      - "3.6"
      - "pypy"
      - "pypy3"
    install:
      - python setup.py bdist_wheel
    script: ls -l dist/
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - autotools-dev
      - libicu-dev
