language: python
notifications:
  email: false
sudo: required
matrix:
  fast_finish: true
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - pip install -U pip wheel
  - git clone https://github.com/01org/hyperscan.git
  - mkdir -p hyperscan/build
  - cd hyperscan/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -G "Unix Makefiles" -DBUILD_SHARED_LIBS=ON ../
  - make
  - make install
  - python setup.py bdist_wheel
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - autotools-dev
      - libboost-dev
      - libicu-dev
